// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyB3brXsMHMDA-qcXpxanJ1oCO6yRsVT-JA',
    appId: '1:159541035932:web:3d082f9c2964382c7f7e59',
    messagingSenderId: '159541035932',
    projectId: 'spotify-clone-fd0d5',
    authDomain: 'spotify-clone-fd0d5.firebaseapp.com',
    storageBucket: 'spotify-clone-fd0d5.appspot.com',
    measurementId: 'G-2D7RH5BKVZ',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyDOh3wmjDUMO-E5qbFkq2c3sclI9N-6LPY',
    appId: '1:159541035932:android:925c75dd42ecd1387f7e59',
    messagingSenderId: '159541035932',
    projectId: 'spotify-clone-fd0d5',
    storageBucket: 'spotify-clone-fd0d5.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyC2Xeit4k4cHMZxeJ776qut6pZQlRyhuRk',
    appId: '1:159541035932:ios:6d2fcaeb9a6f94207f7e59',
    messagingSenderId: '159541035932',
    projectId: 'spotify-clone-fd0d5',
    storageBucket: 'spotify-clone-fd0d5.appspot.com',
    iosBundleId: 'com.example.spotifyClone',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyC2Xeit4k4cHMZxeJ776qut6pZQlRyhuRk',
    appId: '1:159541035932:ios:6d2fcaeb9a6f94207f7e59',
    messagingSenderId: '159541035932',
    projectId: 'spotify-clone-fd0d5',
    storageBucket: 'spotify-clone-fd0d5.appspot.com',
    iosBundleId: 'com.example.spotifyClone',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyB3brXsMHMDA-qcXpxanJ1oCO6yRsVT-JA',
    appId: '1:159541035932:web:7fcc4029d228ca187f7e59',
    messagingSenderId: '159541035932',
    projectId: 'spotify-clone-fd0d5',
    authDomain: 'spotify-clone-fd0d5.firebaseapp.com',
    storageBucket: 'spotify-clone-fd0d5.appspot.com',
    measurementId: 'G-12Z4T9SQFR',
  );
}
